[build]
    publish = "public"
    command = "npm run build"
    functions = "functions"

[[redirects]]
    from = "/api/*"
    to = "https://swapi-graphql.netlify.app/.netlify/functions/index"
    status = 200