[build]
    publish = "build/"
    command = "npm run build"
    functions = "./functions"

[[redirects]]
    from = "/api/*"
    to = "https://swapi-graphql.netlify.app/:splat"
    status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"