[build]
    publish = "build/"
    command = "npm run build"
    functions = "./functions"

[[redirects]]
  from = "/api/*"
  to = "https://swapi-graphql.netlify.app/.netlify/functions/index/:splat"
  status = 200
  force = true
[redirects.headers]
    for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
