[build]
    publish = "build/"
    command = "npm run build"
    functions = "./functions"

[[redirects]]
  from = "/api/*"
  to = "https://swapi-graphql.netlify.app/.netlify/functions/index/:splat"
  status = 200
  force = true
[redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "32b490c6-e39b-4706-87b1-65787f25f04b"
